create database suburbs;
use suburbs;


CREATE TABLE packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    number_of_suburbs INT NOT NULL,
    option_name VARCHAR(18) NOT NULL,
    option_description VARCHAR(150) NOT NULL,
    per_month DECIMAL(6,2) NOT NULL DEFAULT 0,
    per_year DECIMAL(6,2) NOT NULL DEFAULT 0,
    once_off DECIMAL(6,2) NOT NULL DEFAULT 0
);

INSERT INTO packages (number_of_suburbs,option_name, option_description, per_month, per_year,once_off) values 
(1,'Option 1', 'Website listing One Facebook self-service business advert per week (Mondays only)', 90, 900, 140),
(1,'Option 2', 'Website listing Two Facebook self-service business adverts per week (Mondays & Thursdays only)', 120, 1200, 170),
(2,'Option 3', 'Website listing One Facebook self-service business advert per week (Mondays only)', 180, 1800, 230),
(2,'Option 4', 'Website listing Two Facebook self-service business adverts per week (Mondays & Thursdays only)', 240, 2400, 290),
(3,'Option 5', 'Website listing One Facebook self-service business advert per week (Mondays only)', 270, 270, 320),
(3,'Option 6', 'Website listing Two Facebook self-service business adverts per week (Mondays & Thursdays only)', 360, 3600, 410),
(4,'Option 7 (10%)', 'Website listing One Facebook self-service business advert per week (Mondays only)', 324, 3240, 374),
(4,'Option 8 (10%)', 'Website listing Two Facebook self-service business adverts per week (Mondays & Thursdays only)', 432, 4320, 482),
(5,'Option 9 (15%)', 'Website listing One Facebook self-service business advert per week (Mondays only)', 382, 3820, 432),
(5,'Option 10 (15%)', 'Website listing Two Facebook self-service business adverts per week (Mondays & Thursdays only)', 510, 5100, 560),
(6,'Option 11 (20%)' , 'Website listing One Facebook self-service business advert per week (Mondays only)', 432, 4320, 482),
(6,'Option 12 (20%)', 'Website listing Two Facebook self-service business adverts per week (Mondays & Thursdays only)', 576, 5760, 626),
(7,'Option 13 (25%)', 'Website listing One Facebook self-service business advert per week (Mondays only)', 472, 4720, 522),
(7,'Option 14 (25%)', 'Website listing Two Facebook self-service business adverts per week (Mondays & Thursdays only)', 672, 6720, 722);


CREATE TABLE areas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    area_description VARCHAR(255) NOT NULL UNIQUE,
    isActive boolean NOT NULL DEFAULT true
);

INSERT INTO areas (area_description, isActive) values 
('Atlantic Seaboard', true),
('Cape Flats', false),
('City Bowl', true),
('Helderberg', true),
('Northern Suburbs', true),
('South Peninsula', true),
('Southern Suburbs', true),
('West Coast', true);

select * from areas;

CREATE TABLE categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category_description VARCHAR(255) NOT NULL UNIQUE,
    isActive boolean NOT NULL DEFAULT true
);

-- NEW FILE

alter table categories add column image_url varchar(100)

INSERT INTO categories (category_description, isActive) values 
('Accomodation', true),
('Automative', true),
('Adult', true),
('Arts & Crafts', true),
('Events', true),
('Financial', true),
('Garden', true),
('House & Home', true),
('IT & Technology', true),
('Kids', true),
('Legal', true),
('Medical', true),
('Pets', true),
('Pregnancy(Babies)', true),
('Property', true),
('Travel & Tourism', true),
('Transport', true),
('Wellness & Beauty', true);

INSERT INTO categories (category_description, isActive, image_url) values 
('Jewelry & Accessories', true, '/images/areas/jewelryaccessories.png'),
('Photography', true, '/images/areas/jewelryaccessories.png')
INSERT INTO categories (category_description, isActive) values 
('Photography', true)

-- INSERT INTO categories (category_description, isActive, image_url) values 
-- ('Jewelry & Accessories', true, '/images/areas/jewelryaccessories.png'),
-- ('Photography', true, '/images/areas/jewelryaccessories.png')

update categories set image_url = "/images/categories/accomodation.png" where id = 1;
update categories set image_url = "/images/categories/automotive.png" where id = 2;
update categories set image_url = "/images/categories/businessservices.png" where id = 3;
update categories set image_url = "/images/categories/artscrafts.png" where id = 4;
update categories set image_url = "/images/categories/events.png" where id = 5;
update categories set image_url = "/images/categories/financial.png" where id = 6;
update categories set category_description = "Garden & Home", image_url = "/images/categories/garden.png" where id = 7;
update categories set image_url = "/images/categories/househome.png" where id = 8;
update categories set image_url = "/images/categories/ittechnology.png" where id = 9;
update categories set image_url = "/images/categories/kids.png" where id = 10;
update categories set image_url = "/images/categories/decor.png" where id = 11;
update categories set image_url = "/images/categories/medical.png" where id = 12;
update categories set image_url = "/images/categories/pets.png" where id = 13;
update categories set image_url = "/images/categories/pregnancybabies.png" where id = 14;
update categories set image_url = "/images/categories/property.png" where id = 15;
update categories set image_url = "/images/categories/traveltourism.png" where id = 16;
update categories set image_url = "/images/categories/transport.png" where id = 17;
update categories set image_url = "/images/categories/wellnessbeauty.png" where id = 18;
update categories set image_url = "/images/categories/fooddrink.png" where id = 19;
update categories set image_url = "/images/categories/jewelryaccessories.png" where id = 20;
update categories set image_url = "/images/categories/photography.png" where id = 20;


select * from categories;


-- /images/profiles/2Business3Pic.png
-- /images/profiles/2Business3Pic.jpg
NEW
INSERT INTO `client_profiles` (`id`, `businessName`, `first_name`, `last_name`, `mob_no`, `website`, `facebook`, `instagram`, `areas`, `selectedOption`, `catarea`, `profile_description`, `profile_image`, `business_image1`, `business_image2`, `business_image3`, `created_at`, `profile_approved`, `paid_to_date`, `payment_expires`, `extra_packages`, `password`, `ratings`, `email`) VALUES
INSERT INTO `client_profiles` (`id`, `businessName`, `first_name`, `last_name`, `mob_no`, `email`, `website`, `facebook`, `instagram`, `linkedin`, `feedback`, `areas`, `selectedOption`, `catarea`, `product_service`, `adminAssist`, `profile_heading`, `profile_description`, `profile_image`, `business_image1`, `business_image2`, `business_image3`, `created_at`, `terms`, `profile_approved`, `paid_to_date`, `payment_expires`) VALUES
Old



   CREATE TABLE client_profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    businessName VARCHAR(60) NOT NULL UNIQUE,
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    mob_no VARCHAR(13) NOT NULL,
    email VARCHAR(30) NOT NULL,
    website VARCHAR(60) NOT NULL DEFAULT 'No info Provided',
    facebook VARCHAR(60) NOT NULL DEFAULT 'No info Provided',
    instagram VARCHAR(60) NOT NULL DEFAULT 'No info Provided',
    linkedin VARCHAR(60) NOT NULL DEFAULT 'No info Provided',
    feedback VARCHAR(60) NOT NULL DEFAULT 'No info Provided',
    areas JSON NOT NULL,
    selectedOption int NOT NULL,
    catarea JSON NOT NULL,
    product_service varchar(25) not null,
    adminAssist boolean not null,
    profile_heading varchar(25) not null,
    profile_description text not null,
    profile_image VARCHAR(60),
    business_image1 VARCHAR(60),
    business_image2 VARCHAR(60),
    business_image3 VARCHAR(60),
    created_at timestamp default now(),
    terms VARCHAR(30) NOT NULL DEFAULT 'Monthly',
    profile_approved boolean default false,
    paid_to_date boolean default false,
    payment_expires timestamp default now()
    );

-- alter table client_profiles modify column payment_expires timestamp default '2000-01-01'






    desc client_profiles;


create table users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    Upassword VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP DEFAULT NOW(),
    resettoken varchar(20),
    resetexpiry TIMESTAMP DEFAULT NOW()
); 

insert into users (email, Upassword) values ('lisa@suburbsdirectory.co.za', 'password'), ('nicole@suburbsdirectory.co.za', 'password');

CREATE TABLE charities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    businessName VARCHAR(60) NOT NULL UNIQUE,
    npo_number VARCHAR(30),
    first_name VARCHAR(60) NOT NULL,
    last_name VARCHAR(60) NOT NULL,
    mob_no VARCHAR(13) NOT NULL,
    email VARCHAR(30) NOT NULL,
    website VARCHAR(60) NOT NULL DEFAULT 'No info Provided',
    facebook VARCHAR(60) NOT NULL DEFAULT 'No info Provided',
    areas INT NOT NULL,
    profile_description text not null,
    charity_image VARCHAR(60),
    bankName varchar(50),
    branchName varchar(50),
    accountNumber varchar(50),
    branchCode varchar(20),
    created_at timestamp default now(),
    isActive boolean not null default false,
    FOREIGN KEY (areas) REFERENCES areas(id)
);

-- to load asap
alter table charities add column charity_image1 varchar(60);
alter table charities add column charity_image2 varchar(60);
alter table charities add column charity_image3 varchar(60);



CREATE TABLE notices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    heading VARCHAR(60) NOT NULL,
    notice_text text not null,
    created_at timestamp default now()
);

CREATE TABLE faq (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    faq_description text not null,
    created_at timestamp default now()
);



-- NEW





CREATE TABLE extra_packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    option_name VARCHAR(100) NOT NULL,
    option_description VARCHAR(150) NOT NULL,
    per_month DECIMAL(6,2) NOT NULL DEFAULT 0   
);

INSERT INTO extra_packages (option_name, option_description, per_month) values 
('Constantia & Surrounds', 'A piggy back site to join', 25),
('Admin Assist', 'Let us assist you with loading your adverts', 80),
('Cover Photo', 'Have a monthly cover photo', 1200),
('Bishops Court Community Group', 'A piggy back site to join', 25),
('Upper Claremont Community Group', 'A piggy back site to join', 25);




alter table client_profiles add column email varchar(45) not null unique;
alter table client_profiles add column password varchar(255) not null

alter table client_profiles add column ratings float default 0;
alter table client_profiles drop column profile_heading;
alter table client_profiles drop column linkedIn;
alter table client_profiles drop column feedback;
alter table client_profiles drop column terms;
alter table client_profiles drop column product_service;
alter table client_profiles drop column adminAssist;
alter table client_profiles modify column email unique; 
alter table packages drop column per_year;
alter table packages drop column once_off;


update packages set per_month = 90 * number_of_suburbs where option_description like 'Website listing One Facebook self-service business advert per week (Mondays only)'
update packages set per_month = 120 * number_of_suburbs where option_description like 'Website listing Two Facebook self-service business adverts per week (Mondays & Thursdays only)'

create table profile_ratings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    profile_number INT Not Null,
    rating DECIMAL(2,1) not null,
    narrative text not null,
    created_at timestamp default now(),
    FOREIGN KEY (profile_number) REFERENCES client_profiles(id)
);

create table tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    done boolean default false,
    headline varchar(160) not null,
    title varchar(160) not null,
    subtitle text not null,
    created_at timestamp default now()
);



 
insert into client_profiles (id, businessName, first_name, last_name, mob_no, website, facebook, instagram, areas, selectedOption, catarea, profile_description, profile_image, business_image1, business_image2, business_image3, created_at, profile_approved, paid_to_date, payment_expires, password, email) values
(1,'Eccentric Toad','Wayne','Bruton','740628742','https://www.eccentrictoad.com','https://www.facebook.com/eccentrictoad/','https://www.instagram.com/waynebruton1966/','[1, 3, 4, 5, 6, 7, 8]',14,'[9]','At Eccentric Toad I try to design efficient, applicable web apps that are aesthetically pleasing as much as they accomplish what they are set out to do.  When I design a web app, I really try to delve in and understand my customer and understand their business in order to give them the best experience possible during design and the satisfaction of a web app that they have integrally been part of the creative process. I just love it!!  Whether your need is simply to showcase your business and or products, has an interactive flavour for clients to order or purchase goods or a website app that has hundreds of users enabling your business to be as dynamic and productive as possible, Eccentric Toad can make it happen.  I love being creative and designing unique and different websites from scratch. Playing around with HTML, CSS and other tools really stimulates my creative side. I loved creating the <strong>Suburbs Directory</strong>  I am Wayne, live in beautiful Cape Town with my Wife Hazel, two dogs, a really noisy Ringneck Parrot and a whole bunch of fish.','/images/profiles/1ProfilePic.jpg','/images/profiles/1Business1Pic.jpg','/images/profiles/1Business2Pic.jpg','/images/profiles/1Business3Pic.jpg','2019-03-29 09:40:28',1,1,'2019-11-29 18:40:28','password','wayne@eccentrictoad.com'),
(2,'Grey Cement Concepts ','Amy-Leigh','Hvidsten ','726975620','','https://www.facebook.com/Grey-cement-concepts-15850981681889','@grey.amyleigh','[6, 7]',4,'[8]','Grey Cement Concepts is a South African based company who supplies handmade decor items to individuals, curio shops, decor houses and designers.   All of our items are handmade, with attention to detail being of utmost importance.   We have a large range of items, from jewellery to house and home decor.   Cement products offer a fresh, modern look to any one or any space. All of our supplies are sourced locally and all of our items are made to order.   Grey was conceptualised in 2017 and has since grown from strength to strength, the heart behind Grey is the hope to see our products be of both value and standard, we want to see our products in a diversity of homes, being enjoyed by all. ','/images/profiles/2ProfilePic.jpg','/images/profiles/2Business1Pic.jpg','/images/profiles/2Business2Pic.jpg','/images/profiles/2Business3Pic.jpg','2019-03-30 09:31:47',1,1,'2019-11-29 18:40:28','password','grey.amyleigh@gmail.com'),
(3,'Peninsula Tree Fellers ','Roy','Mitchell','799003513','https://www.peninsulatreefellers.co.za/','https://www.facebook.com/peninsulatreefellers/','','[1, 3, 6, 7]',7,'[7]','We are a reputable Tree Felling company based in the Southern Suburbs of the Western Cape. Our team are trained and owner supervised, with many years of tree felling and rope access experience. We are a fully ensured company for your peace of mind.  We pride ourselves on client satisfaction and work ethic.   ','/images/profiles/3ProfilePic.jpg','/images/profiles/3Business1Pic.jpg','/images/profiles/3Business2Pic.jpg','/images/profiles/3Business3Pic.jpg','2019-03-30 10:25:29',1,1,'2019-11-29 18:40:28','password','peninsulatreefellers@gmail.com'),
(4,'Jumping Connor Hire','Lee-Ann','Laufs','715849367','www.jumpingconnor.co.za','https://www.facebook.com/jumpingconnorhire/','','[7]',1,'[10]','We hire out all jumping castles of all sizes from the standard 4m x 4m to castle combos and some themed castles too.  We also have a ball pond (3m x 3m), water pond and water slide.  We deliver, set up and collect.  If you do not have access to electricity for the jumping castle, you can hire our generator at an additional charge (Ts&Cs apply).  We service the southern suburbs and surrounding areas.  ','/images/profiles/4ProfilePic.jpg','/images/profiles/4Business1Pic.jpg','/images/profiles/4Business2Pic.jpg','/images/profiles/4Business3Pic.jpg','2019-03-30 12:04:09',1,1,'2019-11-29 18:40:28','password','hiring@jumpingconnor.co.za'),
(5,'Bob the Builder','Wayne','Bruton','12345','http://www.eccentrictoad.com','','Wayne Bruton','[1]',1,'[1]','Key Achievements: Split the Trust and Nursing College financials, and created a set of consolidated financials to comply with the companies act. Implemented ETI (Employee Tax Incentive) and back dated it resulting in a net cash saving to the organisation of approximately R850,000 to date. Created a management reporting and Board pack by linking directly to the Pervasive database via MS Excel so the pack refreshes and updates automatically  Responsibilities: Preparing the General Ledger with Creditors, Debtors and Sales entries, and coordinating with the bankers in handling the bank accounts, online payments and EFT’s Developing monthly management reports for the Trustee meetings of all projects, including variance reports, forecasts and major cash flow statements   Performing Risk Management duties for the organisation, carrying out risk audits and the implementation of various risk control strategies Ensuring the timely submission of Income Tax and VAT returns, along with the organisations Tax Clearance Certificate Administering the monthly payment of salaries for over 60 staff members and 180 carers, while overseeing payments and returns for SARS and Pension Fund Preparing the annual budget for the organisation, including the Nursing College Ensuring adequate insurance for the property and vehicles and assessing all forms of Capex including vehicles, property, IT costs and other assets Was in charge of maintenance and had a maintenance team reporting to me Responsible for fleet management Directly responsible for IT and had an IT supervisor reporting to me Was responsible for Occupational health and safety Was on the Employment Equity committee ','/images/profiles/5ProfilePic.jpg','/images/profiles/5Business1Pic.jpg','/images/profiles/5Business2Pic.jpg','/images/profiles/5Business3Pic.jpg','2019-04-01 12:36:10',1,0,'2019-11-29 18:40:28','password','waynebruton@icloud.com'),
(6,'Coax PR and Communications ','Henda ','Kellerman ','727324310','http://www.coax.co.za','http://www.facebook.com/coaxcomms','http://www.instagram.com/coaxcomms','[5, 7]',3,'[3]','I am a local PR consultant with a taste for all things digital. I specialise in website design, social media setup, digital marketing, blogging, brand and content development (including colour consulting and brand boards) and proofreading &amp; editing. As a PR Consultant it is my job to take away the guesswork and streamline your branding and marketing initiatives behind the scenes, allowing you the freedom to go on with business as usual. I can help my clients through all the stages of public relations, communication and online reputation management.  Specialised Services: Blogging | Website Design | Social Media Setup | Brand Development | Logo Design | Business Cards | Stationery | Content Development | Digital Marketing | Consultation &amp; Project Management | Proofreading &amp; Editing | Public Relations | Layout &amp; Artwork *I offer these services at reduced rates, without compromising on quality.  My service is a direct and personal commitment to your brand. I follow a unique process of conceptualisation and strategic planning that ensures design projects are delivered on time, in-budget and upholding the highest standards. The result: a high-end, crease-free project that establishes you as a respected industry leader while your brand is distinguished from the competition.','/images/profiles/6ProfilePic.jpg','/images/profiles/6Business1Pic.jpg','/images/profiles/6Business2Pic.jpg','/images/profiles/6Business3Pic.jpg','2019-04-01 13:27:20',1,1,'2019-11-29 18:40:28','password','henda@coax.co.za'),
(7,'Scribble Designs','Angela','Mouton','823535113','http://www.scribbledesigns.co.za','http://www.facebook.com/scribbledesignssa','http://www.instagram.com/scribbledesignssa/','[6]',1,'[8]','Scribble Designs offers unique décor items, baby clothing and gifts, designed and manufactured locally in Cape Town, South Africa.  Contact us on hello@scribbledesigns.co.za or 082 3535 113 for more information. ','/images/profiles/7ProfilePic.jpg','/images/profiles/7Business1Pic.jpg','/images/profiles/7Business2Pic.jpg','/images/profiles/7Business3Pic.jpg','2019-04-01 16:25:21',0,1,'2019-11-29 18:40:28','password','hello@scribbledesigns.co.za'),
(8,'Nicole Webb Mobile Spa','Nicole','Webb','799265950','','https://www.facebook.com/nicolewebbmobilespa/','','[5]',1,'[18]','We bring the spa to you! Let us take care of the tedious travelling and bring the luxury spa experience to your door, be it at work, home, hospital, or hotel. Enjoy having your nails, lashes and waxing done professionally in the comfort of your own home. We provide all the equipment necessary to give you an all around rejuvenation spa experience.  ','/images/profiles/8ProfilePic.jpg','/images/profiles/8Business1Pic.jpg','/images/profiles/8Business2Pic.jpg','/images/profiles/8Business3Pic.jpg','2019-04-03 11:18:01',1,1,'2019-11-29 18:40:28','password','nicolewebbnaildesigns@gmail.co'),
(9,'Peninsula Drillers ','Roy','Mitchell','799003513','','https://www.facebook.com/peninsuladrillers/?modal=admin_todo','','[7]',1,'[7]','Peninsula Drillers are a highly recommended mud rotary borehole drilling company in the Southern Suburbs. With an experienced driller and owner supervision on site you can rest assured that each project is a priority to us. We have a large database of happy clients who can attest this our competitive quotes and excellent customer service. ','/images/profiles/9ProfilePic.jpg','/images/profiles/9Business1Pic.jpg','/images/profiles/9Business2Pic.jpg','/images/profiles/9Business3Pic.jpg','2019-04-04 10:30:04',1,1,'2019-11-29 18:40:28','password','peninsuladrillers@gmail.com'),
(10,'ACS Naturals','Antonie','Gericke','766591973','http://www.acsnaturals.co.za ','https://www.facebook.com/acsnaturals/','','[7]',1,'[7]','We are a Southern Suburbs based business offering the following services in and around the area:   - Landscaping - Full garden maintenance, once off clean ups, mow and go.  - Special rose care lawn care.  - Garden and other refuse removal. - We make wooden fences, gates and wooden plant boxes. - Firewood - available for your lekker braai or for your indoor fireplace.  - Supply and source plants. - Tree trimming, poisoning and tree removal.  Contact us today for a competitive quote. ','/images/profiles/10ProfilePic.jpg','/images/profiles/10Business1Pic.jpg','/images/profiles/10Business2Pic.jpg','/images/profiles/10Business3Pic.jpg','2019-04-05 10:19:57',1,1,'2019-11-29 18:40:28','password','info@acsnaturals.co.za'),
(11,'Giloi & Co ','Erika ','Giloi ','837996804','http://www.giloiandco.co.za','https://www.facebook.com/giloiandco/','','[6, 7]',4,'[3]','So far I am a one-woman-band here to provide small local start-ups with affordable assistance I team up with other local smaller one-man-band businesses to give you everything that you need Great one-on-one service - no big agency no big agency fees!   Affordable service with exceptional quality You are not compromising your vision by going small - you are supporting local business while achieving your goals and ours!','/images/profiles/11ProfilePic.jpg','/images/profiles/11Business1Pic.jpg','/images/profiles/11Business2Pic.jpg','/images/profiles/11Business3Pic.jpg','2019-04-08 16:02:15',1,1,'2019-11-29 18:40:28','password','giloierika@gmail.com'),
(12,'Mr Metsan Dry Carpet Cleaning Company ','Colin / Yvonne ','Berger ','832616804','','','','[6, 7]',4,'[8]','As most people residing in the Western Cape should know, saving water has become part of our daily routine. We are a local business who offer DRY cleaning of carpets, curtains, blinds, rugs and upholstery. We use NO water, steam or foam and your items will be dry on completion.  ','/images/profiles/12ProfilePic.jpg','/images/profiles/12Business1Pic.jpg','/images/profiles/12Business2Pic.jpg','/images/profiles/12Business3Pic.jpg','2019-04-09 09:31:19',1,1,'2019-11-29 18:40:28','password','colvon@iafrica.com'),
(13,'Content Kids ','Candice ','Voss','823791701','http://www.content-kids.com','https://www.facebook.com/Content-kids-580004039112889/','','[1, 3, 6, 7]',8,'[10]','My name is Candice Voss I have a psychology background and have worked as an au pair facilitator at mainstream schools and as a therapist at a specialised therapy intervention centre for children with social emotional communication challenges and behavioural difficulties For the past several years I worked at an NPO focusing on Autism family support parent and professional workshops behaviour management school support and training as well as support at Tygerberg Hospital and Red Cross Children’s Hospital Content-Kids is my private practice where I focus on parenting support inclusive education and teacher support as well as special needs support with a specific focus on autism behavior management and alternative communication systems ','/images/profiles/13ProfilePic.jpg','/images/profiles/13Business1Pic.jpg','/images/profiles/13Business2Pic.jpg','/images/profiles/13Business3Pic.jpg','2019-04-11 12:10:18',1,1,'2019-11-29 18:40:28','password','candy@content-kids.com'),
(14,'The Art Of Perfume','Melaney','van Rensburg','814095237','','','','[6]',1,'[18]','The Art of Perfume offers over 200 popular fragrances for both women and men with OVER 130 of these in stock and available immediately. Our fragrances are expertly created using the finest quality fragrant oils imported from France, as well as other reputable fragrance houses in Europe. They are manufactured as Eau de Parfum strength 25 pure perfume oil and not the weaker Eau de Toilette strength and therefore highly concentrated to last all day. Our fragrances are generic and inspired by the most famous designer scents adding new additions to our range every month. We pride ourselves on the quality of our products and therefore offer a 100% money back guarantee. We also offer liquid hand soaps, hand and body lotions, shower gels and car air fresheners. ALL IN YOUR FAVOURITE DESIGNER SCENTS!','/images/profiles/14ProfilePic.jpg','/images/profiles/14Business1Pic.jpg','/images/profiles/14Business2Pic.jpg','/images/profiles/14Business3Pic.jpg','2019-04-12 09:00:58',1,1,'2019-11-29 18:40:28','password','theartofperfume1@gmail.com'),
(15,'Peninsula Airport Transfers','Sven','Berg','713818857','','','','[6, 7]',3,'[3, 16, 17]','Peninsula Airport Transfers offer transfers to and from Cape Town International Airport. Operating in the Southern Peninsula and Southern Suburbs only. Please contact Sven on 071 381 8857 to receive a quote.','/images/profiles/15ProfilePic.jpg','/images/profiles/15Business1Pic.jpg','/images/profiles/15Business2Pic.jpg','/images/profiles/15Business3Pic.jpg','2019-04-20 17:53:25',0,0,'2019-11-29 18:40:28','password','nicolebergcapetown@gmail.com'),
(16,'Under Wraps','Shelley ','Van Der Walt ','829980441','http://www.underwraps.africa ','https://www.facebook.com/UnderWrapsweightedtherapyproducts/','https://www.instagram.com/underwrapsweightedproducts/','[1, 3, 5, 6, 7]',9,'[10]','We provide custom weighted therapy products that assist children and adults battling with anxiety, stress, hyperactivity or broken, restless sleep. The weighted pressure helps to modify behaviour by increasing feelings of safety, which improves concentration, focus and energy levels. ','/images/profiles/16ProfilePic.jpg','/images/profiles/16Business1Pic.jpg','/images/profiles/16Business2Pic.jpg','/images/profiles/16Business3Pic.jpg','2019-04-24 09:08:18',1,1,'2019-11-29 18:40:28','password','shelley@underwraps.africa'),
(17,'Aloe Unique','Samantha','Olckers','217854483','http://www.aloeunique.co.za','https://www.facebook.com/AloeUniqueSouthAfrica ','https://www.instagram.com/aloeuniquesouthafrica/?hl=en','[5, 6]',4,'[18]','Aloe Unique brings you a range of skin care treatments containing the powerful active ingredients of the Aloe Ferox plant. Containing almost twice as many amino acids as Aloe Vera, Aloe Ferox is ideal for skin care as it has been scientifically proven to penetrate the skin to the deepest layer. The Aloe Ferox plant is rich in amino acids, the powerful agent Aloin, as well as polysaccharides and other plant metabolites so it contributes to a soft and smooth skin that is hydrated, nourished and rejuvenated.','/images/profiles/17ProfilePic.jpg','/images/profiles/17Business1Pic.jpg','/images/profiles/17Business2Pic.jpg','/images/profiles/17Business3Pic.jpg','2019-04-24 12:00:00',1,1,'2019-11-29 18:40:28','password','sales@aloeunique.com'),
(18,'The Salmon Lady ','Lindie ','Gorrie','810411653','','https://www.facebook.com/Thesalmonlady/','','[7]',2,'[19]','With their backgrounds firmly rooted in the restaurant industry Warren and Lindie Gorrie have sourced salmon of extremely high quality Their supplier with 25 years’ experience is well established in the salmon business and is the preferred supplier to various five-star establishments Warren is a qualified chef internationally recognised by the City amp; Guilds of London Institute and has worked in kitchens in Vail Colorado and in and around Cape Town Lindie has experience in the restaurant industry in a managerial position Salmon is well known to have many health benefits It has been known to help with weight loss strengthen bones it acts as an anti-inflammatory and reduces the risk of depression and the combination of Omega-3s and vitamin D can lower the risk of chronic disease   Please go ahead and order some of our delicious Salmon and other products','/images/profiles/18ProfilePic.jpg','/images/profiles/18Business1Pic.jpg','/images/profiles/18Business2Pic.jpg','/images/profiles/18Business3Pic.jpg','2019-04-30 09:25:54',1,1,'2019-11-29 18:40:28','password','lindie.gorrie1@gmail.com'),
(19,'Moutons Towing ','Andrew ','Mouton','832659795','www.moutonstowing.co.za','https://www.facebook.com/moutonstowing/','','[6]',2,'[2]','Moutons Towing has been around for nearly 30 years offering 24 hours towing and roadside assistance to road users of the South Peninsula and surrounding areas ','/images/profiles/19ProfilePic.jpg','/images/profiles/19Business1Pic.jpg','/images/profiles/19Business2Pic.jpg','/images/profiles/19Business3Pic.jpg','2019-04-30 14:14:06',1,1,'2019-11-29 18:40:28','password','moutons@mweb.co.za'),
(20,'ABZ Electrical','Jaun','Meyer','792876331','','http://www.facebook.com/ABZ-Electrical-782460825484546','','[6, 7]',3,'[3]','Are you in need of appliance repairs Look no further!! With trained technicians and experience staff you know you are in good hands We work on the all type models and makes such as Samsung LG Defy Bosch Kelvinator SMEG Indesit Hisense and all other makes We work on Washing Machines Dishwashers Tumble-Dryers OvensStoves FridgesFreezers TVRadios With direct suppliers you know we do it at the lowest cost Fully reg company backing us you know who you can trust Feel free to contact us at any time for more information or booking!! 079 287 6331 or admin@abzelectricalcoza  ','/images/profiles/20ProfilePic.jpg','/images/profiles/20Business1Pic.jpg','/images/profiles/20Business2Pic.jpg','/images/profiles/20Business3Pic.jpg','2019-05-01 12:40:33',0,0,'2019-11-29 18:40:28','password','admin@abzelectrical.co.za'),
(21,'TLC Flooring, Blinds & Outdoor','Ron ','Roos ','217011503','www.tlcflooring.co.za ','https://www.facebook.com/tlcflooring/','https://www.instagram.com/tlcflooringcapetown/','[6, 7]',4,'[8]','TLC Flooring is a wooden flooring and blinds company based in Cape Town.  We supply and fit a wide variety of Blinds in the greater Cape Town area and offer the most competitive blinds pricing and installation in the Cape, which makes TLC Blinds Cape Town the preferred blinds company.   We specialise in the supply of top quality products at competitive prices. We supply and install a variety of Wooden Flooring (Laminate and Engineered Wood), Luxury Vinyl Flooring, Carpets, Blinds, and Rugs.   TLC Specialist Flooring Solutions’ track record in installing South African brand name carpets, vinyl flooring, solid wood floors, a variety of quality laminate floorings and warmup floor heating systems is well known. ','/images/profiles/21ProfilePic.jpg','/images/profiles/21Business1Pic.jpg','/images/profiles/21Business2Pic.jpg','/images/profiles/21Business3Pic.jpg','2019-05-02 09:01:41',1,1,'2019-11-29 18:40:28','password','ron@tlcflooring.co.za'),
(22,'TLC Outdoor ','Ron ','Roos ','217011503','www.tlcflooring.co.za ',' https://www.facebook.com/tlcflooring/','https://www.instagram.com/tlcflooringcapetown/','[6, 7]',3,'[7]','TLC Flooring is a wooden flooring and blinds company based in Cape Town who now also specialise in Synthetic Grass.   We supply and fit a wide variety of Blinds in the greater Cape Town area and offer the most competitive blinds pricing and installation in the Cape, which makes TLC Blinds Cape Town the preferred blinds company. We specialise in the supply of top quality products at competitive prices. We supply and install a variety of Wooden Flooring (Laminate and Engineered Wood), Luxury Vinyl Flooring, Carpets, Blinds, Rugs and Synthetic Grass.   TLC Specialist Flooring Solutions’ track record in installing South African brand name carpets, vinyl flooring, solid wood floors, a variety of quality laminate floorings and warmup floor heating systems as well as synthetic grass is well known in and around the suburbs of the Western Cape.  ','/images/profiles/22ProfilePic.jpg','/images/profiles/22Business1Pic.jpg','/images/profiles/22Business2Pic.jpg','/images/profiles/22Business3Pic.jpg','2019-05-02 09:24:03',1,1,'2019-11-29 18:40:28','password','ron@tlcflooring.co.za'),
(23,'RGS Steel Cape Town','Robbie','Stemmet ','848090000','','https://web.facebook.com/RGSSteel/','','[6, 7]',4,'[7, 8]','RGS offers an on site service as well as in house fabrication. We have been involved in various projects from gates, fencing, burglar bars, garden features, general on site repairs, furniture, structural supply, installations and any general steel design work. ','/images/profiles/23ProfilePic.jpg','/images/profiles/23Business1Pic.jpg','/images/profiles/23Business2Pic.jpg','/images/profiles/23Business3Pic.jpg','2019-05-02 15:18:40',1,1,'2019-11-29 18:40:28','password','rgstemmet@gmail.com'),
(24,'Cape Outdoor Decking','Zak','Scheepers','829263765','https://www.capeoutdoordecking.co.za/home.html','','','[1, 3, 6, 7]',7,'[8]','Timber Decking is our a popular means to transform any outdoor and even indoor spaces into areas that escape day to day life stresses. Timber offers a way to create an environment where your family and friends can switch off into the ambiance of any chosen natural surroundings. Let our consultants help you create a room, home or any outdoor patio or pool areas into that special place for your family and friends. ','/images/profiles/24ProfilePic.jpg','/images/profiles/24Business1Pic.jpg','/images/profiles/24Business2Pic.jpg','/images/profiles/24Business3Pic.jpg','2019-05-03 08:10:53',1,1,'2019-11-29 18:40:28','password','info@capeoutdoordecking.co.za'),
(25,'deckscapes cc','charles','de jongh','722235985','http://www.deckscapes.co.za','https://www.facebook.com/woodendecking/','http://www.instagram.com/d3ck52010/','[1, 3, 4, 5, 6, 7]',11,'[7, 8]','Deckscapes vision is to be one of the leading timber decking and timber design businesses in the Western Cape. The Deckscapes skilled team offer unique timber solutions for any area in and round your business or home. The ability to satisfy our customer needs and complete projects with pedantic perfectionism has ensured Deckscapes’ longevity and growth. Each job is attended to with top quality craftsmanship and the resulting structurally sound timber projects are loved by Deckscapes clients. Deckscapes build decks. The best kind. The most durable and highest quality timber with top quality craftsmanship is applied. Decking companies usually only build decks. With Deckscapes, in addition to creating beautiful decks, the skills offered are building and designing unique projects on any landscape. Projects such as jetties installation, pergolas, timber frame extensions and privacy screens , stairs, timber fences, walls and gates are all within the Deckscapes scope of business. The Deckscapes attentive team make sure you enjoy your building experience while adding value to your home or property.','NULL','NULL','NULL','NULL','2019-05-09 11:56:47',1,0,'2019-11-29 18:40:28','password','charles@deckscapes.co.za'),
(26,'The Curtain Company ','Carolynne ','Franklin ','217012288','http://www.thecurtaincompany.co.za ','https://www.facebook.com/thecurtaincompany/','','[6, 7]',3,'[8]','We have been manufacturing and installing curtains, blinds and soft furnishings for over 30 years. Our in-house seamstresses and installers ensure a one-stop experience where accountability and attention to detail are key.  We are accredited agents for all of the fabric houses in the country and have a showroom where you may browse fabric samples at your leisure. Our business partners offer interior design and project consultations for both domestic and corporate clients with boutique guest houses and retirement villages a speciality. We consult, measure, make and install - all with our fabric or yours. Our upholstery partners are world renowned for their custom-made items, and the manufacturers of our roller and venetian blinds allow us to ensure the very best quality is provided to our valued clients.','/images/profiles/26ProfilePic.jpg','/images/profiles/26Business1Pic.jpg','/images/profiles/26Business2Pic.jpg','/images/profiles/26Business3Pic.jpg','2019-05-13 11:13:28',1,1,'2019-11-29 18:40:28','password','info@thecurtaincompany.co.za'),
(27,'Doorstep Dairyman ','Rudi','Swart ','842517504','http://www.doorstepdairyman.co.za ','https://www.facebook.com/DoorstepDairyman/','https://www.pictame.com/user/doorstepdairyman/8600174620','[7]',2,'[19]',"Doorstep dairyman is the mobile delivery service for all your door to door dairy needs! We deliver a variety of fresh dairy products directly to your home or place of work. We have partnered with a few local companies to bring you some of their awesome products too! Our prices are competitive and our service is not just great but also incredibly convenient.  Our aim is to supply you with fresh, daily and delicious produce all right to your doorstep. We are big on social responsibility and that is why we choose to be and active business who contributes back to the communities that we work in, by partnering with local NPO's and giving R1 of every Bennies pie that gets sold to Miracle Kidz Safe House!! Join us by treating yourself, all while supporting a charity in becoming financially more secure - Its a win win.   You can register for our services on our website. Keep a close look out for our specials, new products and exciting partnerships on our Facebook and Instagram accounts.  ",'/images/profiles/27ProfilePic.jpg','/images/profiles/27Business1Pic.jpg','/images/profiles/27Business2Pic.jpg','/images/profiles/27Business3Pic.jpg','2019-05-16 09:31:35',1,1,'2019-11-29 18:40:28','password','rudiswart@gmail.com'),
(28,'Swimlab Swim School – Constantia','Di ','Rigotti','713130714','http://www.swimlab.co.za','http://www.facebook.com/Swimlab-Swim-School-Constantia-82316','','[7]',2,'[10]','Swimlab Swim School – Constantia, previously known as Di’s Swim School, has been teaching kids to swim for over 20 years. Offering professional swimming lessons and coaching for little ones, on all levels in a indoor and heated environment.  Individual Learn to Swim lessons (one on one with an instructor) Baby groups Squad swimming (2-4 swimmers per group) Buddy Swim Lesson  Our instructors are all registered and qualified with Learn to Swim South Africa and Western Province Aquatics and possess CPR and level 1 first aid certificates.  We are qualified to teach infants (from 6 months), beginners, stroke correction, water safety and more advanced swimmers.   Constantia – 071 313 0714 Ages from 6 months until 10 years of Age   CONTACT E-MAIL: marketing@swimlab.co.za','/images/profiles/28ProfilePic.jpg','/images/profiles/28Business1Pic.jpg','/images/profiles/28Business2Pic.jpg','/images/profiles/28Business3Pic.jpg','2019-05-21 10:41:06',1,1,'2019-11-29 18:40:28','password','marketing@swimlab.co.za'),
(29,'Q W property improvements ','Quinton ','Wentzel ','788321230','','','','[7]',2,'[8]','QW Property improvements, is a registered general building, construction, maintenance and renovation contractor. We are an NHBRC registered company, registration NO: 8318.   We are committed to being an efficient general contractor working in an ethical and balanced manner. Pursuing excellence through dedication and experience. We have an ongoing passion to deliver quality timeously. We are dedicated in helping our clients dreams to become a reality.   Our mission is to be a dynamic team, providing the highest quality construction services available, whilst being committed to building long term relationships based on integrity, performance, value and client satisfaction.   We will continue to meet the changing needs of our clients with our quality services, delivered by the most qualified people.  ','/images/profiles/29ProfilePic.jpg','/images/profiles/29Business1Pic.jpg','/images/profiles/29Business2Pic.jpg','/images/profiles/29Business3Pic.jpg','2019-05-22 09:18:02',1,1,'2019-11-29 18:40:28','password','qwpropimprove45@gmail.com'),
(30,'Waynes new business','Wayne','Bruton','740628742','https://www.mytoad.co.za','http://www.facebook','Wayne Bruton','[1]',1,'[1]','Key Achievements: • Split the Trust and Nursing College financials, and created a set of consolidated financials to comply with the companies act. • Implemented ETI (Employee Tax Incentive) and back dated it resulting in a net cash saving to the organisation of approximately R850,000 to date. • Created a management reporting and Board pack by linking directly to the Pervasive database via MS Excel so the pack refreshes and updates automatically Responsibilities: • Preparing the General Ledger with Creditors, Debtors and Sales entries, and coordinating with the bankers in handling the bank accounts, online payments and EFT’s • Developing monthly management reports for the Trustee meetings of all projects, including variance reports, forecasts and major cash flow statements • Performing Risk Management duties for the organisation, carrying out risk audits and the implementation of various risk control strategies • Ensuring the timely submission of Income Tax and VAT returns, along with the organisations Tax Clearance Certificate • Administering the monthly payment of salaries for over 60 staff members and 180 carers, while overseeing payments and returns for SARS and Pension Fund • Preparing the annual budget for the organisation, including the Nursing College • Ensuring adequate insurance for the property and vehicles and assessing all forms of Capex including vehicles, property, IT costs and other assets • Was in charge of maintenance and had a maintenance team reporting to me • Responsible for fleet management • Directly responsible for IT and had an IT supervisor reporting to me • Was responsible for Occupational health and safety • Was on the Employment Equity committee','/images/profiles/30ProfilePic.jpg','/images/profiles/30Business1Pic.jpg','/images/profiles/30Business2Pic.jpg','/images/profiles/30Business3Pic.jpg','2019-05-24 08:42:40',0,0,'2019-11-29 18:40:28','password','waynebruton@icloud.com'),
(31,'Yet another business','Wayne','Bruton','4445567777','http://www.eccentrictoad.com','http://www.facebook','Wayne Bruton','[1]',1,'[1]','Key Achievements: • Split the Trust and Nursing College financials, and created a set of consolidated financials to comply with the companies act. • Implemented ETI (Employee Tax Incentive) and back dated it resulting in a net cash saving to the organisation of approximately R850,000 to date. • Created a management reporting and Board pack by linking directly to the Pervasive database via MS Excel so the pack refreshes and updates automatically Responsibilities: • Preparing the General Ledger with Creditors, Debtors and Sales entries, and coordinating with the bankers in handling the bank accounts, online payments and EFT’s • Developing monthly management reports for the Trustee meetings of all projects, including variance reports, forecasts and major cash flow statements • Performing Risk Management duties for the organisation, carrying out risk audits and the implementation of various risk control strategies • Ensuring the timely submission of Income Tax and VAT returns, along with the organisations Tax Clearance Certificate • Administering the monthly payment of salaries for over 60 staff members and 180 carers, while overseeing payments and returns for SARS and Pension Fund • Preparing the annual budget for the organisation, including the Nursing College • Ensuring adequate insurance for the property and vehicles and assessing all forms of Capex including vehicles, property, IT costs and other assets • Was in charge of maintenance and had a maintenance team reporting to me • Responsible for fleet management • Directly responsible for IT and had an IT supervisor reporting to me • Was responsible for Occupational health and safety • Was on the Employment Equity committee','/images/profiles/31ProfilePic.jpg','/images/profiles/31Business1Pic.jpg','/images/profiles/31Business2Pic.jpg','/images/profiles/31Business3Pic.jpg','2019-05-24 08:47:29',0,0,'2019-11-29 18:40:28','password','waynebruton@icloud.com'),
(32,'IN THE ZONE','Kim','Watermeyer','793435953','http://www.inthezone.co.za','http://www.facebook.com/InTheZone.CapeTown','inthezone.capetown','[7]',1,'[4, 10]',"Come and join us and be creative at In The Zone - Art Studio.  We are easy to find above Pick n Pay liquor store, KFC building, Wicklow Road, Plumstead.  You don't have to be able to draw. We gently guide you the whole way. One of our most common student comebacks is: Wow - I can't believe I did that! :)  Our lovely, bright studio is home to the following:  1. ADULT acrylic painting CLASSES (mornings & evenings) 2. KIDS' creative CLASSES (Wednesday afternoons) 3. ART PARTIES for adults and/or children 4. School HOLIDAY workshops 5. Creative WEEKEND workshops for adults (particularly in winter) 6. Small, customised TEAM BUILDS  Rose and Kim champion individual self-expression so that no two student-paintings will ever look the same. Everyone works at their own pace in a very relaxed and friendly environment.  We serve tea and coffee and we have wine glasses, so BYOB is welcomed. It is so much fun - Some of our adult students come twice a week!  For more info: www.inthezone.co.za 079 3466 559 - Rose 079 343 5953 - Kim  Every child is an artist. The problem is how to remain an artist once we grow up. - Picasso",'/images/profiles/32ProfilePic.jpg','/images/profiles/32Business1Pic.jpg','/images/profiles/32Business2Pic.jpg','/images/profiles/32Business3Pic.jpg','2019-05-28 10:42:21',1,1,'2019-11-29 18:40:28','password','info@inthezone.co.za'),
(33,'Fireplace & Chimney Co.','Djamile','Rossouw','217821143','http://www.fireplaceandchimney.co.za','http://www.facebook.com/fireplaceandchimney.co.za','http://www.instagram.com/fireplaceandchimneyco','[5, 6, 7]',5,'[7, 8]','At Fireplace and Chimney Co, we strive to make your fireplace dreams a reality. With hundreds of fireplaces priced from as little as R5990, we have something for everyone. Our showroom is located in Fish Hoek and we have a user friendly website (www.fireplaceandchimney.co.za) to help make your choice easier. We have installed hundreds of fireplaces over the last 18 years and also service and refurb fireplaces. To add to that we also offer an advanced chimney sweeping service. Call us now on 021-7821143 or email sales@fireplaceandchimney.co.za or make an appointment for one of our friendly experts to visit your home to help you make your choice. Fireplace and Chimney Co........now everyone can afford a fireplace.','NULL','NULL','NULL','NULL','2019-05-28 21:41:56',0,0,'2019-11-29 18:40:28','password','jim@fireplaceandchimney.co.za'),
(34,'Sugar & Spice nanny training ','Kim ','Lee-ann','827433076','http://www.nannytraining.co.za','https://www.facebook.com/SugarandSpiceNannyTraining/','','[7]',2,'[20]','We guide the nannies through a practical, interactive and fun learning process, discussing and teaching principles of routines, time management and child safety; first aid; nutrition and hygiene; and growth and development.','/images/profiles/34ProfilePic.jpg','/images/profiles/34Business1Pic.jpg','/images/profiles/34Business2Pic.jpg','/images/profiles/34Business3Pic.jpg','2019-05-31 11:23:36',1,1,'2019-11-29 18:40:28','password','kim@nannytraining.co.za'),
(35,'Trauma Share','Anna','els','733556807','','','','[5, 7]',1,'[12]','I am a wellness and trauma counsellor who also does drug and addiction counselling.  I look after the wellness of staff at companies. I am more than just a voice over the telephone. I go to companies and speak to the staff regarding wellness and relevant issues (domestic violence, abuse, personal, marriage, ext). I also do one on one counselling with the staff that needs to talk or have issues to be help with. I try to work pro active and solve problems before it cause problems at work.  Personal problems can cause staff to loose focus at work, which cause problems for the company. I see that the staff are happy and can focus on their jobs and management can focus on their jobs. They don’t have to deal with the nitty gritty of day to day problems. The well being of the staff is important as the staff are an asset and not a liability. They are the future of the company. ','/images/profiles/35ProfilePic.jpg','/images/profiles/35Business1Pic.jpg','/images/profiles/35Business2Pic.jpg','/images/profiles/35Business3Pic.jpg','2019-06-03 08:39:26',1,0,'2019-11-29 18:40:28','password','traumashare01@gmail.com'),
(36,'Cobs Corner Montessori Pre-School','Mark','Mark','714032169','http://www.cobscorner.co.za','https://www.facebook.com/Cobs-Corner-Montessori-School-15458','','[6]',1,'[10, 20]','Cobs Corner Montessori Pre-School for boys and girls is situated in Kirstenhof, Cape Town. Cobs Corner offers a warm, nurturing, child-centered learning environment from the ages of 18 months upwards. We focus on each childs individual needs, maintaining small classes, allowing us to place emphasise on their development and potential.  Our qualified staff teach: Functional independence Cognitive,  Physical,  Emotional,  Social,  Language  Aesthetic skills while gently guiding each child towards the fundamental principles of development in a well prepared, conducive environment.  A sunny school with lots of natural light where we promote work, play, interaction, music, pre-numeracy skills and creativity from baking to movement and music including arts and crafts where children are free to interact with their environment in a safe, loving and nurturing space. ','/images/profiles/36ProfilePic.jpg','/images/profiles/36Business1Pic.jpg','/images/profiles/36Business2Pic.jpg','/images/profiles/36Business3Pic.jpg','2019-06-04 10:44:00',1,1,'2019-11-29 18:40:28','password','info@cobscorner.co.za'),
(37,'The Nice Company','Sean','Moncrieff','27217016037','http://thenicecompany.co.za/','https://www.facebook.com/thenicecompanyZA/','https://www.instagram.com/thenicecompanyza/','[6, 7]',1,'[19]','The Nice Company is a classic artisan company producing fresh dairy ice cream, frozen yoghurt and fruits sorbets.  The Nice Company is a classic artisan company who have been producing fresh dairy ice cream, frozen yoghurt and fruit sorbets for over 20 years. We are dedicated to the process of original recipes, but excited and alert to inventive and contemporary developments in food. You could say that we have old fashioned values and an inventive modern sensibility. Hence the motto: THERES NOTHING NEWER THAN OLD FASHIONED ICE CREAM.  ','/images/profiles/37ProfilePic.jpg','/images/profiles/37Business1Pic.jpg','/images/profiles/37Business2Pic.jpg','/images/profiles/37Business3Pic.jpg','2019-06-19 13:40:57',1,1,'2019-11-29 18:40:28','password','info@thenicecompany.co.za'),
(38,'Natural Paving pvt','Wayne','Kanini','795826649','','','','[8]',1,'[7]',' ~Paving Repairs   ~New installations  ~Cost effective paving  •half brick   •cement brick paving   •cobble paving   •block paving   •Clay brick paving   •pool corping  •concrete floors  •interlocking   Contact us @','/images/profiles/38ProfilePic.jpg','/images/profiles/38Business1Pic.jpg','/images/profiles/38Business2Pic.jpg','/images/profiles/38Business3Pic.jpg','2019-06-29 09:41:04',1,0,'2019-11-29 18:40:28','password','waynekanini@yahoo.com'),
(39,'BERG DIGITAL MARKETING','Nicole','Berg','813998309','','https://www.facebook.com/BERG-Digital-Marketing-434531800432','@bergrsa','[1, 3, 4, 5, 6, 7, 8]',13,'[3]','BERG DIGITAL MARKETING offers a variety of online marketing services including social media management, content creation, product photography, service photography and business photography. Contact us today for a comprehensive list of all our available packages.  ','/images/profiles/39ProfilePic.jpg','/images/profiles/39Business1Pic.jpg','/images/profiles/39Business2Pic.jpg','/images/profiles/39Business3Pic.jpg','2019-07-02 16:23:35',1,1,'2019-11-29 18:40:28','password','nicolebergcapetown@gmail.com'),
(40,'Expressions for Hair @ Home','Megan','Bosman','217944161','n/a','https://www.facebook.com/expressionsforhair/','https://www.instagram.com/expressionsforhair/','[7]',1,'[18]','Boutique hair salon based in Avery Avenue, Constantia, Cape Town.  Professional service and quality products from a truly passionate team who love what they do.  To book contact Adam: 082 394 5064 or Kathi: 083 395 9072','/images/profiles/40ProfilePic.jpg','/images/profiles/40Business1Pic.jpg','/images/profiles/40Business2Pic.jpg','/images/profiles/40Business3Pic.jpg','2019-07-09 12:57:33',1,1,'2019-11-29 18:40:28','password','megan@honeycombdigital.co.za'),
(41,'Dr Joel Oliveira ','Dr Joel ','Oliveira','662012927','','https://www.facebook.com/Dr-Joel-Oliveira-GP-249725080365232','','[7]',2,'[12]','Dr Joel would like to introduce himself as a new practitioner in the Constantia area. He is a dedicated family man practicing from his home on Doordrift road.  He has devoted almost 20 years to general medical practice and building a report with his patients. At the new practice the following services are offered:  General medical examinations including men’s health, Management of chronic illnesses such as Diabetes, Hypertension, Management of mood disorders, General illnesses, General Paediatric illnesses, Insurance Medicals, Stress ECGs, Minor surgical procedures, Dr Joel can assist with home visits for frail, elderly or very ill patients that are unable to travel. Looking forward to the pleasure of meeting you.  I am currently not contracted into medical aids. An invoice will be emailed that you can use to claim back from your medical aid. The consultations are R400 cash or R500 if paid by EFT and home visits are R600.','/images/profiles/41ProfilePic.jpg','/images/profiles/41Business1Pic.jpg','/images/profiles/41Business2Pic.jpg','/images/profiles/41Business3Pic.jpg','2019-07-15 10:11:30',1,1,'2019-11-29 18:40:28','password','drjoel.oliveira@gmail.com'),
(42,'TImber Style Structures ','Belinda ','Winter ','796153495','http://www.timberstylestructures.co.za','https://www.facebook.com/Timber-Style-Structures-29929409384','','[6, 7]',1,'[8]','TIMBER STYLE STRUCTURES  Thinking of building?  TIMBER FRAME CONSTRUCTION WITH A NUTEC OR PLASTERBOARD FINISH, COULD BE THE ANSWER.  Do you need a loft conversion, Garden cottage or separate office space?  OR  " Why not build above your existing Garage or Home and save garden space"?  No need to move out while we build upward on your home.  We specialises in converting the unused area of your roof into a valuable living area, providing the most economical and convenient way to create space and adding additional value to your property.   Ideal for:  Extra income ( B&amp;B), Office space or  Extra accommodation for the family.  "Building plans and Engineers fees are included in our quotations".  "Light weight construction, NO need to underpin your existing foundations".','/images/profiles/42ProfilePic.jpg','/images/profiles/42Business1Pic.jpg','/images/profiles/42Business2Pic.jpg','/images/profiles/42Business3Pic.jpg','2019-07-19 09:12:57',1,1,'2019-11-29 18:40:28','password','timberstructures@telkomsa.net'),
(43,'Stir Crazy Cooking School','Brenda / Lanah ','Arnold ','217907165','http://www.stircrazycooking.co.za','https://www.facebook.com/CookWithStirCrazy/?ref=br_rs','https://www.instagram.com/stircrazycookingschool/','[3, 7]',3,'[19]','Stir Crazy Cooking School is an authentic ‘hands-on’ short course cooking school in Cape Town. We offer a wide variety of short cooking courses that are ideal for anyone interested in learning a new cooking skill or style, or for those who merely want to come and enjoy an evening out with friends. All classes are taught by professional chefs who have either been in the restaurant trade or whom have owned their own restaurants. Each chef is a specialist in their own culinary skill, and they’ll impart their knowledge, experience and stories with you during classes. Participants get involved in preparing delicious course recipes which are then shared around a dinner table afterward, so you get to sample everything prepared on the evening. Our classes are relaxed, informative and interactive making your experience with Stir Crazy truly memorable. Although some of our classes are demonstration classes, most of our classes are hands-on cooking classes so you can really get involved in creating our delicious recipes.  ','/images/profiles/43ProfilePic.jpg','/images/profiles/43Business1Pic.jpg','/images/profiles/43Business2Pic.jpg','/images/profiles/43Business3Pic.jpg','2019-08-02 10:37:06',1,1,'2019-11-29 18:40:28','password','lanah@stircraxycooking.co.za'),
(44,'Ludovica Barnato Dog Behaviourist & Trainer ','Ludovica ','Barnato','818513330','http://www.ludovicabarnato.co.za ','https://www.facebook.com/Barnatotraining/','','[1]',1,'[13]','Puppy classes in Seapoint!  Fun, force free classes run by certified behaviourist Ludovica Barnato in collaboration with Dogz at home training centre.   Where: Pugsley &amp; Wednesday Doggie Daycare, Seapoint (indoors evening classes)  Any pups under 16 weeks welcome to join.   For more info and booking please contact Ludovica on 0810513330 or visit ww.ludovicabarnato.co.za ','/images/profiles/44ProfilePic.jpg','/images/profiles/44Business1Pic.jpg','/images/profiles/44Business2Pic.jpg','/images/profiles/44Business3Pic.jpg','2019-08-02 11:37:09',1,1,'2019-11-29 18:40:28','password','ludovica@barnato.co.za'),
(45,'The Om Revolution ','Hayley','Speakman ','638680899','http://www.theomrevolution.co.za','https://web.facebook.com/theomrevolutioncapetownyoga/','https://www.instagram.com/theomrevolution/','[1, 3, 5, 7]',7,'[18]','We provide private, group, corporate and pregnancy yoga classes at any desired location. Whether it is in the comfort and privacy of your own home, or the convenience of your office, or that beautiful beach down the road - we bring the benefits, balance, fitness, strength and inner peace of Yoga practice to you.   We specialize in:  Corporate yoga classes that help staff of all ages and sizes release stress and become more positive and productive. Private yoga classes that are convenient and tailored specifically for your needs and expectations. Full attention from your instructor help you achieve better results quicker. Group yoga classes that allow you and your group of friends or family experience and learn this awesome activity together, whenever and wherever you like. Yoga experiences that take you to the most breathtaking locations across Cape Town for a down dog like no other!  We also stock:  Cork Alignment Mats Made from recycled, natural cork, this mat is the ideal surface for your Yoga practice    Our professional and experienced team of yoga instructors will turn anyone into a Yogi! ','/images/profiles/45ProfilePic.jpg','/images/profiles/45Business1Pic.jpg','/images/profiles/45Business2Pic.jpg','/images/profiles/45Business3Pic.jpg','2019-08-02 14:09:26',1,1,'2019-11-29 18:40:28','password','yoga@theomrevolution.co.za'),
(46,'The Framer ','Kim ','Boyes ','822675201','http://www.theframer.co.za ','https://www.facebook.com/theframerclaremont/?ref=br_rs','','[7]',2,'[8]','We are a framing business who supply and stock a wide range of moulding and mount boards.   We do block mounting, canvas stretching, box frames, memorabilia, photographs, certificates and matric art work.   We also sell a limited range of art and photography. We aim to support local artists.  ','/images/profiles/46ProfilePic.jpg','/images/profiles/46Business1Pic.jpg','/images/profiles/46Business2Pic.jpg','/images/profiles/46Business3Pic.jpg','2019-08-05 10:27:14',1,1,'2019-11-29 18:40:28','password','kim@theframer.co.za'),
(47,'Rest Assured House & Pet Sitting Services','Dano','Taljaard','842570151','','https://www.facebook.com/pg/restassuredwithdano/photos/?ref=','','[7]',2,'[8, 13]','Hi all I’m a very reliable 21-year-old male, offering my house and pet sitting services. I have plenty of experience with animals as my mom runs a pet sitting service where she cares for the needs of animals on our property throughout the year. I have been  exposed to this for a long time and have the necessary skills to provide your animals with the attention and care that they need. I am trustworthy, reliable, honest, and clean (I don’t drink or smoke). I am currently a third year Law student.   I offer stay-in services, where I will be happy to stay at your house and take over any routine that may need to be carried out (caring for your pets, watering the garden, cleaning the pool, keeping the security in check, etc.) I will be situated in Cape Town  and surrounds, Northern and Southern Suburbs, Cape Winelands, etc. Pretty much anywhere. Please don’t hesitate to ask any questions, I’ll be happy to provide more information. You can contact me by commenting, sending me a whatsapp: 084 257 0151 Alternatively  you can email me @ danotaljaard@outlook.com or inbox me on facebook  REFERENCES can be found on my page:  Rest Assured House and Pet Sitting Services By Dano ','/images/profiles/47ProfilePic.jpg','/images/profiles/47Business1Pic.jpg','/images/profiles/47Business2Pic.jpg','/images/profiles/47Business3Pic.jpg','2019-08-05 12:05:03',1,1,'2019-11-29 18:40:28','password','danotaljaard@outlook.com'),
(48,'Ambrosia Catering (Frozen Meals)','Beatrice','McShane','837387115','http://www.ambrosia-catering.co.za','https://www.facebook.com/ambcateringfreezermeals/','','[7]',1,'[19]','Ambrosia Catering has been cooking up a storm since 1997 (22 years in the Catering Industry having catered for many Events/Functions), we noticed a need in the market for Healthy, Affordable, Home cooked Frozen Meals, and our Frozen Meal Department was born 3 years ago.  We have numerous Clients/Customers who order from us on a weekly and monthly basis and are very happy with our Meals.  We have 2 sizes:  300g serves 1 person 500g serves 2 people  All our Dishes are frozen and come in microwaveable foil containers, soups come in pouches.  We have a large variety of Meat, Chicken and Pasta dishes including 100% Banting and Vegetarian Meals.  We have a same day delivery service if your order is placed before 12pm. Deliveries are Monday - Friday (3-6pm)  Our payments options are as follows:  Online credit/debit card payment EFT or CASH YOCO (transportable credit/debit card machine)  Order Process:  Order online at: www.ambrosia-catering.co.za email: info@ambrosia-catering.co.za  We look forward to making Meal Times easier for You and Your Family!!     ','/images/profiles/48ProfilePic.jpg','/images/profiles/48Business1Pic.jpg','/images/profiles/48Business2Pic.jpg','/images/profiles/48Business3Pic.jpg','2019-08-05 14:58:23',1,1,'2019-11-29 18:40:28','password','info@ambrosia-catering.co.za'),
(49,'Divenire Rhythmic Gymnastics','Candice','Uys','639228495','','https://web.facebook.com/divenirerhythmic/?epa=SEARCH_BOX','https://www.instagram.com/candiceuys/','[7]',1,'[10]','Rhythmic Gymnastics, an Olympic sport, is a beautiful combination of gymnastics, ballet, dance and acrobatics incorporating hoops, balls, ribbons, clubs and ropes. Divenire Rhythmic Gymnastics Club is owned and coached by SA gymnast, Candice Uys. We offer a variety of training for girls from age 4. Classes take place at Vera School in Rondebosch East, which is easily accessible.  The class schedule is available on the Facebook page and free trial classes are also offered! ','/images/profiles/49ProfilePic.jpg','/images/profiles/49Business1Pic.jpg','/images/profiles/49Business2Pic.jpg','/images/profiles/49Business3Pic.jpg','2019-08-05 16:06:25',1,1,'2019-11-29 18:40:28','password','divenireRG@gmail.com'),
(50,'Crest Tutoring ','Anneke ','Potgieter ','763798806','https://cresttutoring.wixsite.com/capetown','https://web.facebook.com/cresttutoring/?ref=br_rs','https://www.instagram.com/cresttutoring/','[7]',1,'[10, 20]','Crest Tutoring is a Cape Town-based tutoring agency that specialises in private and group tutorials for the subject Afrikaans First Additional Language.  Our mission is to provide our students with the highest quality of educational support whilst catering to their specific needs and personalities. We also endeavour to encourage an appreciation for the Afrikaans language and the culture associated with it. Private lessons are presented in the comfort of your own home in central Cape Town, the southern suburbs or South Peninsula. Our tutors travel to you at no additional cost, saving you valuable driving time. Group lessons can be arranged at a reduced rate for a group of friends in the same grade. Such sessions are especially useful for revision purposes before exams, provided your child does not need specific, individual attention.  If you would like to find out whether we have a tutor available for you, please fill in the form on our website: https://cresttutoring.wixsite.com/capetown/get-a-tutor. ','/images/profiles/50ProfilePic.jpg','/images/profiles/50Business1Pic.jpg','/images/profiles/50Business2Pic.jpg','/images/profiles/50Business3Pic.jpg','2019-08-08 12:17:00',1,1,'2019-11-29 18:40:28','password','cresttutoring@gmail.com'),
(51,'Happy Dusters Cleaning Services ','Nicole ','Geary ','671311610','http://www.happydusters.co.za ','https://www.facebook.com/happydusterscleaningservices/','https://www.instagram.com/happydusterscleaningservices/','[6, 7]',4,'[3, 8]','Is housework stopping you from doing what you want to do? Do you need a local, regular, reliable, trustworthy, vetted cleaner to work in your home, to your specification and, at a time convenient to you? Would you like a cleaner to eliminate those time-consuming chores, allowing you to spend quality time with your family and friends? Our well-trained staff are able to assist every requirement where cleaning has to be provided around the home. They can also assist with decluttering and garage storage cleaning. ','/images/profiles/51ProfilePic.jpg','/images/profiles/51Business1Pic.jpg','/images/profiles/51Business2Pic.jpg','/images/profiles/51Business3Pic.jpg','2019-08-13 09:27:46',1,1,'2019-11-29 18:40:28','password','info@happydusters.co.za'),
(52,'Pop Up Emporium ','Lisa','Osrin','826607447','http://www.popupemporium.co.za','https://www.facebook.com/POP-UP-EMPORIUM-368068387153678/','https://www.instagram.com/popupemporium/','[1, 3, 5, 6, 7]',10,'[5]','A pop-up shopping experience / market. Join us every two months for new and exciting offerings - a shopping experience with a difference. Hosted at different venues. ','/images/profiles/52ProfilePic.jpg','/images/profiles/52Business1Pic.jpg','/images/profiles/52Business2Pic.jpg','/images/profiles/52Business3Pic.jpg','2019-09-04 09:55:22',1,1,'2019-11-29 18:40:28','password','lisa@lisaosrin.co.za'),
(53,'Soliette Skincare ','Lauren ','Blyth ','722715429','www.soliette.co.za','https://www.facebook.com/solietteskincare/','https://www.instagram.com/soliette.skincare/','[1, 7]',3,'[18]','At Soliette Skincare, we create a luxurious spa experience with bespoke treatments, tailor-made for your specific skin requirements, suited to your budget. Together we create a synergistic skincare regime with home care and salon treatments, to maximise the long term benefits to your skincare goals.','/images/profiles/53ProfilePic.jpg','/images/profiles/53Business1Pic.jpg','/images/profiles/53Business2Pic.jpg','/images/profiles/53Business3Pic.jpg','2019-09-04 10:55:33',1,1,'2019-11-29 18:40:28','password','info@soliette.co.za'),
(54,'Surf Emporium ','Mikayla ','Roxy','217888687',' https://surfemporium.co.za/','https://www.facebook.com/surfemporium/','','[3, 6, 7]',6,'[5, 16]','Surf Emporium is internationally renowned as South Africa’s most popular Surf and SUP destination with a proven track record. Surf Emporium, located on the Muizenberg beach front Surfers Corner, offers an accredited Surf and SUP School, high quality equipment rental hub, retailer of leading Surf and SUP brands and a Vida e Cafè all under one roof.','/images/profiles/54ProfilePic.jpg','/images/profiles/54Business1Pic.jpg','/images/profiles/54Business2Pic.jpg','/images/profiles/54Business3Pic.jpg','2019-09-11 11:15:45',1,1,'2019-11-29 18:40:28','password','mikayla@surfemporium.co.za'),
(55,'Blue Gum Country Estate ','Tarryn ','De Kock ','832641317','http://www.bluegum.co.za','http://www.facebook.com/bluegumestate/','http://www.instagram.com/bluegumcountryestate/','[1, 3, 4, 5, 6, 7]',11,'[1, 10, 16, 19]','Accommodation, Restaurant &amp; Wine Farm in STANFORD, the Heart of the Overberg  Named after the 150-year old Blue Gum Tree that grows on our front lawn, the Estate is both a working farm dating back to 1839 and a Private, Family-run Guest House. We pride ourselves on offering visitors a unique experience in a welcoming environment. We also place great value in our Staff, and as a result you’ll find that everyone is actively responsible for making your stay memorable. We want you to feel like you’re in a Private Home – but with NO obligation to your Hosts. As our Guest, we’ll make sure you’re taken care of, down to the last detail.  Whether you stay in the Manor House, Mountain View or our Blue Gum Rooms, you’ll discover a Tranquil Retreat that offers something for everyone from Honeymoon Couples to Solo Travellers and Large Family Groups. With this in mind we have 2 Dining Rooms on the Estate: Our Family Dining Room is open for Breakfast, Lunch and Dinner daily, while our more Formal Dining Room is open for Dinner, and caters to Adults only. Breakfast is included in the Room Rates. We also have experienced Babysitters, who need to be booked in advance at an Additional Cost. ','/images/profiles/55ProfilePic.jpg','/images/profiles/55Business1Pic.jpg','/images/profiles/55Business2Pic.jpg','/images/profiles/55Business3Pic.jpg','2019-09-19 09:43:47',1,1,'2019-11-29 18:40:28','password','tarryn@bluegum.co.za'),
(56,'Sight and Sound ','Lee-Ann','Laufs ','215101425','http://www.sightandsound.co.za','https://www.facebook.com/sightandsoundav/','','[5, 6, 7]',5,'[5]','From humble beginnings, Sight &amp; Sound was established in 1974 by Mike Sack, a pioneer in the hiring of technical equipment for the tourism and event industry.  Roy Haines joined Mike in 1994 and together they built a strong brand and company culture.  Now in our 45th year of business, we can safely say we are one of the oldest Technical Event Production Companies in South Africa.  Despite our growth and massive achievements, we are still an owner-run business.  Marc and Nicky Taylor, who started in junior positions in 1997 now run the company together, 21 years later.  We have evolved in leaps and bounds since the days of hiring out binoculars, slide projectors, flip charts and tripod screens and although we now offer a full-spectrum of services, we have never forgotten what our business is built on:    Strong, meaningful relationships and good old-fashioned service.    With a synonymous history of putting our clients first, we still proudly support many clients countrywide, who have relied on our expertise since the very beginning.  With a strong focus on company culture and looking after our clients, without ever forgetting where we have come from, we look forward to partnering with you for the next 45 years!','/images/profiles/56ProfilePic.jpg','/images/profiles/56Business1Pic.jpg','/images/profiles/56Business2Pic.jpg','/images/profiles/56Business3Pic.jpg','2019-09-19 15:20:54',1,1,'2019-11-29 18:40:28','password','power@sightandsound.co.za'),
(57,'Caversham Educational Institute ','Lee-Ann ','Laufs ','784220047','https://cavershaminstitute.co.za/','https://www.facebook.com/CavershamEducationInstitute/','','[7]',1,'[20]','If you are passionate about young children and if you believe that a career in teaching this age group is not only important but vital to the future of individuals, families and ultimately our country then we have the course for you!  ','/images/profiles/57ProfilePic.jpg','/images/profiles/57Business1Pic.jpg','/images/profiles/57Business2Pic.jpg','/images/profiles/57Business3Pic.jpg','2019-09-20 13:49:23',1,1,'2019-11-29 18:40:28','password','admin@cavershaminstitute.co.za'),
(58,'Nat Gold ZA ','Natalie ','Goldsmith ','729918303','http://www.natgoldza.co.za ','http://www.facebook.com/NatGoldZA/','http://www.instagram.com/natgold_za/','[6, 7]',1,'[10, 13, 14, 15]','When I was a child, my mother would tell me: ‘Use your seeing eye’. I have brought this particular way of looking at the world to all my enterprises: from my first job as a newspaper photographer, fish packing in Iceland, a bakery in London and managing holiday houses in Betty’s Bay, to my current adventure, which is Digital photography, with an emphasis on pets. What I love about photographs is their longevity: they live on beyond the moment. I imagine people decades later revisiting the images that will bring back the happy memories made with their fur family members Sessions always include a print of your favourite because digital files tend to end up forgotten on our computers or phones. Hopefully, my images inspire you to get your loyal, four-legged companion captured in a beautiful portrait that will last forever. They also make great gifts!','/images/profiles/58ProfilePic.jpg','/images/profiles/58Business1Pic.jpg','/images/profiles/58Business2Pic.jpg','/images/profiles/58Business3Pic.jpg','2019-10-22 08:51:07',1,1,'2019-11-29 18:40:28','password','natgoldza@telkomsa.net');
